import type {
  User,
  Item,
  BorrowRequest,
  Review,
  AppNotification,
} from "./types";
import { addDaysISO, todayISO } from "./helpers";

/**
 * LendLoop seed data — a small Filipino neighborhood ("barangay") of lenders
 * and borrowers. All names, items, and copy are context-appropriate marketing
 * copy (Marketing skill): no Lorem ipsum, no filler.
 *
 * Dates are computed relative to "today" at module load so the prototype always
 * shows a living calendar (borrow windows, due dates, recent activity).
 */

/* ------------------------------------------------------------------ users */

export const CURRENT_USER_ID = "u_maya";
export const ADMIN_USER_ID = "u_admin";

export const seedUsers: User[] = [
  {
    id: "u_maya",
    name: "Maya Santos",
    email: "maya@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=47",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-02-10T08:00:00.000Z",
    bio: "Weekend DIY-er and plantita. Happy to lend my tools so neighbors don't have to buy new.",
    phone: "+63 917 555 0142",
  },
  {
    id: "u_admin",
    name: "Captain Ramon Reyes",
    email: "admin@lendloop.ph",
    password: "admin123",
    avatar: "https://i.pravatar.cc/150?img=12",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "admin",
    status: "active",
    verified: true,
    joinedAt: "2023-11-01T08:00:00.000Z",
    bio: "Barangay captain and LendLoop community steward. Keeping the loop safe and fair.",
    phone: "+63 917 555 0001",
  },
  {
    id: "u_jose",
    name: "Jose Dela Cruz",
    email: "jose@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=33",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-01-05T08:00:00.000Z",
    bio: "Carpenter by trade. Tools deserve to work, not gather dust.",
  },
  {
    id: "u_ana",
    name: "Ana Villanueva",
    email: "ana@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=45",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-03-19T08:00:00.000Z",
    bio: "Home organizer and renter-friendly DIY champion.",
  },
  {
    id: "u_ben",
    name: "Ben Tan",
    email: "ben@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=15",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-04-22T08:00:00.000Z",
    bio: "Mountaineer. My gear earns its keep between trips.",
  },
  {
    id: "u_liza",
    name: "Liza Mendoza",
    email: "liza@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=31",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-05-08T08:00:00.000Z",
    bio: "Film buff and backyard movie night host.",
  },
  {
    id: "u_mark",
    name: "Mark Aguilar",
    email: "mark@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=51",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-06-14T08:00:00.000Z",
    bio: "Home baker. Order ka ng cake, huwag lang gamit ang mixer ko. :)",
  },
  {
    id: "u_gina",
    name: "Gina Rocero",
    email: "gina@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=20",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "active",
    verified: true,
    joinedAt: "2024-07-02T08:00:00.000Z",
    bio: "Kapihan host and fiesta prepper. May kaldero ako para sa lahat.",
  },
  {
    id: "u_tony",
    name: "Tony Bautista",
    email: "tony@lendloop.ph",
    password: "bayanihan",
    avatar: "https://i.pravatar.cc/150?img=68",
    barangay: "Barangay Mabini",
    city: "Quezon City",
    role: "user",
    status: "suspended",
    verified: false,
    joinedAt: "2024-08-30T08:00:00.000Z",
    bio: "Late returns, twice. Working my trust back up.",
  },
];

/* ----------------------------------------------------------------- items */

/**
 * Item images use picsum.photos seeded URLs (stable + reliable). The gallery
 * component also renders a CategoryArt gradient fallback if any URL fails.
 */
function img(seed: string) {
  return `https://picsum.photos/seed/${seed}/800/600`;
}

export const seedItems: Item[] = [
  {
    id: "it_drill",
    title: "Cordless Power Drill, 18V",
    description:
      "Reliable 18V cordless drill with two batteries and a full bit set. Perfect for mounting shelves, assembling furniture, or that one weekend project you keep postponing.",
    category: "Tools",
    condition: "Good",
    images: [img("lendloop-drill-1"), img("lendloop-drill-2"), img("lendloop-drill-3")],
    primaryImageIndex: 0,
    ownerId: "u_jose",
    maxBorrowDays: 5,
    deposit: 500,
    bookedDates: [addDaysISO(todayISO(), 3), addDaysISO(todayISO(), 4)],
    status: "available",
    location: "8 Mabini St, Quezon City",
    createdAt: "2024-09-01T08:00:00.000Z",
    views: 142,
  },
  {
    id: "it_ladder",
    title: "Folding Aluminum Ladder (8 ft)",
    description:
      "Lightweight 8-foot aluminum ladder, folds flat for easy carry. Rated to 120kg. Great for changing bulbs, cleaning gutters, or reaching the top shelf of the bodega.",
    category: "Tools",
    condition: "Like New",
    images: [img("lendloop-ladder-1"), img("lendloop-ladder-2")],
    primaryImageIndex: 0,
    ownerId: "u_ana",
    maxBorrowDays: 3,
    deposit: 600,
    bookedDates: [],
    status: "available",
    location: "12 Rizal Ave, Quezon City",
    createdAt: "2024-09-12T08:00:00.000Z",
    views: 88,
  },
  {
    id: "it_tent",
    title: "6-Person Camping Tent",
    description:
      "Spacious dome tent that fits six (comfortably four). Waterproof, quick-setup poles included. Survived two typhoons and a company outing.",
    category: "Outdoor",
    condition: "Good",
    images: [img("lendloop-tent-1"), img("lendloop-tent-2"), img("lendloop-tent-3")],
    primaryImageIndex: 0,
    ownerId: "u_ben",
    maxBorrowDays: 7,
    deposit: 1000,
    bookedDates: [addDaysISO(todayISO(), 10), addDaysISO(todayISO(), 11), addDaysISO(todayISO(), 12)],
    status: "reserved",
    location: "5 Pico St, Quezon City",
    createdAt: "2024-09-20T08:00:00.000Z",
    views: 213,
  },
  {
    id: "it_projector",
    title: "HD Mini Projector + Tripod Screen",
    description:
      "Compact 1080p projector with built-in speaker and a 60-inch foldable screen. Plug in your phone or laptop for a backyard sine night. HDMI cable included.",
    category: "Electronics",
    condition: "Like New",
    images: [img("lendloop-projector-1"), img("lendloop-projector-2")],
    primaryImageIndex: 0,
    ownerId: "u_liza",
    maxBorrowDays: 2,
    deposit: 1200,
    bookedDates: [],
    status: "available",
    location: "22 Aurora Blvd, Quezon City",
    createdAt: "2024-10-02T08:00:00.000Z",
    views: 167,
  },
  {
    id: "it_mixer",
    title: "Stand Mixer, 5-Quart",
    description:
      "Heavy-duty 5-quart stand mixer with dough hook, whisk, and paddle. Powers through bibingka batter and ensaymada dough without breaking a sweat.",
    category: "Kitchen",
    condition: "Like New",
    images: [img("lendloop-mixer-1"), img("lendloop-mixer-2"), img("lendloop-mixer-3")],
    primaryImageIndex: 0,
    ownerId: "u_mark",
    maxBorrowDays: 3,
    deposit: 800,
    bookedDates: [addDaysISO(todayISO(), 1)],
    status: "available",
    location: "9 Kamias Rd, Quezon City",
    createdAt: "2024-10-10T08:00:00.000Z",
    views: 95,
  },
  {
    id: "it_kaldero",
    title: "Large Kaldero & Carajay Set",
    description:
      "Fiesta-sized cast aluminum kaldero (perfect for kare-kare) plus a wide carajay for lechon kawali and ginataan. Feeds 30–40 hungry neighbors.",
    category: "Kitchen",
    condition: "Good",
    images: [img("lendloop-kaldero-1"), img("lendloop-kaldero-2")],
    primaryImageIndex: 0,
    ownerId: "u_gina",
    maxBorrowDays: 2,
    deposit: 400,
    bookedDates: [],
    status: "available",
    location: "3 Sto. Niño St, Quezon City",
    createdAt: "2024-10-15T08:00:00.000Z",
    views: 71,
  },
  {
    id: "it_speaker",
    title: "Bluetooth Party Speaker w/ Mic",
    description:
      "Belt-out-your-harana speaker with a wireless mic, disco lights, and 8-hour battery. Karaoke-ready, fiesta-approved. Walls may shake.",
    category: "Party",
    condition: "Good",
    images: [img("lendloop-speaker-1"), img("lendloop-speaker-2")],
    primaryImageIndex: 0,
    ownerId: "u_gina",
    maxBorrowDays: 2,
    deposit: 700,
    bookedDates: [],
    status: "available",
    location: "3 Sto. Niño St, Quezon City",
    createdAt: "2024-10-18T08:00:00.000Z",
    views: 188,
  },
  {
    id: "it_bike",
    title: "Mountain Bike, 27.5\"",
    description:
      "Hardtail 27.5\" mountain bike with 21 gears and hydraulic brakes. Helmet and pump included. Take it up Timberland or just around the barangay.",
    category: "Sports",
    condition: "Good",
    images: [img("lendloop-bike-1"), img("lendloop-bike-2"), img("lendloop-bike-3")],
    primaryImageIndex: 0,
    ownerId: "u_ben",
    maxBorrowDays: 4,
    deposit: 1500,
    bookedDates: [],
    status: "borrowed",
    location: "5 Pico St, Quezon City",
    createdAt: "2024-10-22T08:00:00.000Z",
    views: 134,
  },
  {
    id: "it_vacuum",
    title: "Wet/Dry Shop Vacuum",
    description:
      "Heavy-duty 20L wet/dry vacuum. Saws water spills, sawdust, and post-construction dust equally well. Comes with three nozzles.",
    category: "Tools",
    condition: "Fair",
    images: [img("lendloop-vacuum-1")],
    primaryImageIndex: 0,
    ownerId: "u_jose",
    maxBorrowDays: 2,
    deposit: 500,
    bookedDates: [],
    status: "available",
    location: "8 Mabini St, Quezon City",
    createdAt: "2024-10-26T08:00:00.000Z",
    views: 52,
  },
  {
    id: "it_stove",
    title: "Portable Butane Camping Stove",
    description:
      "Compact butane stove with 3 canisters. Boils water in 4 minutes. Ideal for camping, brownout cooking, or your backyard boodle fight.",
    category: "Outdoor",
    condition: "Good",
    images: [img("lendloop-stove-1"), img("lendloop-stove-2")],
    primaryImageIndex: 0,
    ownerId: "u_ben",
    maxBorrowDays: 5,
    deposit: 300,
    bookedDates: [],
    status: "available",
    location: "5 Pico St, Quezon City",
    createdAt: "2024-11-01T08:00:00.000Z",
    views: 64,
  },
  {
    id: "it_books",
    title: "Children's Storybook Bundle (12 pcs)",
    description:
      "A curated bundle of 12 well-loved Filipino and English storybooks. Perfect for a weekend reading corner or a birthday activity table.",
    category: "Books",
    condition: "Good",
    images: [img("lendloop-books-1"), img("lendloop-books-2")],
    primaryImageIndex: 0,
    ownerId: "u_ana",
    maxBorrowDays: 14,
    deposit: 250,
    bookedDates: [],
    status: "available",
    location: "12 Rizal Ave, Quezon City",
    createdAt: "2024-11-05T08:00:00.000Z",
    views: 39,
  },
  {
    id: "it_blender",
    title: "Heavy-Duty Blender",
    description:
      "Crushes ice, makes smoothies, and powers through halo-halo. 1.5L jar. A summer staple for the sago-and-gulaman crowd.",
    category: "Kitchen",
    condition: "Good",
    images: [img("lendloop-blender-1"), img("lendloop-blender-2")],
    primaryImageIndex: 0,
    ownerId: "u_mark",
    maxBorrowDays: 3,
    deposit: 450,
    bookedDates: [],
    status: "available",
    location: "9 Kamias Rd, Quezon City",
    createdAt: "2024-11-08T08:00:00.000Z",
    views: 77,
  },
];

/* -------------------------------------------------------------- requests */

export const seedRequests: BorrowRequest[] = [
  {
    id: "req_1",
    itemId: "it_bike",
    borrowerId: "u_maya",
    ownerId: "u_ben",
    startDate: addDaysISO(todayISO(), -1),
    endDate: addDaysISO(todayISO(), 2),
    message: "Bike camping trip to Timberland this weekend — will return it spotless and pumped. Salamat!",
    status: "borrowed",
    agreementSigned: true,
    signatureName: "Maya Santos",
    createdAt: addDaysISO(todayISO(), -3) + "T10:00:00.000Z",
    borrowedAt: addDaysISO(todayISO(), -1) + "T09:00:00.000Z",
  },
  {
    id: "req_2",
    itemId: "it_drill",
    borrowerId: "u_maya",
    ownerId: "u_jose",
    startDate: addDaysISO(todayISO(), 6),
    endDate: addDaysISO(todayISO(), 8),
    message: "Mounting a new cabinet for the kitchen. Two days should be plenty. Promise to return with all bits.",
    status: "pending",
    agreementSigned: false,
    signatureName: "",
    createdAt: addDaysISO(todayISO(), 0) + "T07:30:00.000Z",
  },
  {
    id: "req_3",
    itemId: "it_tent",
    borrowerId: "u_liza",
    ownerId: "u_ben",
    startDate: addDaysISO(todayISO(), 10),
    endDate: addDaysISO(todayISO(), 12),
    message: "Family camping at La Mesa Eco Park. Need the big tent for the kids. Will air-dry before returning.",
    status: "approved",
    agreementSigned: true,
    signatureName: "Liza Mendoza",
    createdAt: addDaysISO(todayISO(), -2) + "T14:00:00.000Z",
  },
  {
    id: "req_4",
    itemId: "it_speaker",
    borrowerId: "u_mark",
    ownerId: "u_gina",
    startDate: addDaysISO(todayISO(), -10),
    endDate: addDaysISO(todayISO(), -9),
    message: "Birthday celebration for my mom. One night only, promise!",
    status: "returned",
    agreementSigned: true,
    signatureName: "Mark Aguilar",
    createdAt: addDaysISO(todayISO(), -12) + "T09:00:00.000Z",
    borrowedAt: addDaysISO(todayISO(), -10) + "T18:00:00.000Z",
    returnedAt: addDaysISO(todayISO(), -9) + "T10:00:00.000Z",
  },
  {
    id: "req_5",
    itemId: "it_mixer",
    borrowerId: "u_gina",
    ownerId: "u_mark",
    startDate: addDaysISO(todayISO(), -20),
    endDate: addDaysISO(todayISO(), -18),
    message: "Bibingka for the barangay fundraiser. Will return cleaner than I got it.",
    status: "returned",
    agreementSigned: true,
    signatureName: "Gina Rocero",
    createdAt: addDaysISO(todayISO(), -22) + "T11:00:00.000Z",
    borrowedAt: addDaysISO(todayISO(), -20) + "T08:00:00.000Z",
    returnedAt: addDaysISO(todayISO(), -18) + "T16:00:00.000Z",
  },
  {
    id: "req_6",
    itemId: "it_kaldero",
    borrowerId: "u_tony",
    ownerId: "u_gina",
    startDate: addDaysISO(todayISO(), -30),
    endDate: addDaysISO(todayISO(), -27),
    message: " Fiesta prep.",
    status: "returned",
    agreementSigned: true,
    signatureName: "Tony Bautista",
    createdAt: addDaysISO(todayISO(), -32) + "T08:00:00.000Z",
    borrowedAt: addDaysISO(todayISO(), -30) + "T07:00:00.000Z",
    returnedAt: addDaysISO(todayISO(), -26) + "T20:00:00.000Z",
  },
];

/* --------------------------------------------------------------- reviews */

export const seedReviews: Review[] = [
  {
    id: "rev_1",
    fromUserId: "u_mark",
    toUserId: "u_gina",
    itemId: "it_speaker",
    requestId: "req_4",
    rating: 5,
    comment: "Speaker was louder than promised and Gina even included an extra mic cable. Fiesta saved!",
    createdAt: addDaysISO(todayISO(), -9) + "T12:00:00.000Z",
  },
  {
    id: "rev_2",
    fromUserId: "u_gina",
    toUserId: "u_mark",
    itemId: "it_mixer",
    requestId: "req_5",
    rating: 5,
    comment: "Mixer worked like new, picked up on time, returned spotless. Salamat, Mark!",
    createdAt: addDaysISO(todayISO(), -18) + "T17:00:00.000Z",
  },
  {
    id: "rev_3",
    fromUserId: "u_gina",
    toUserId: "u_tony",
    itemId: "it_kaldero",
    requestId: "req_6",
    rating: 2,
    comment: "Returned a day late with a small dent. Communicated only after I followed up. Needs to do better.",
    createdAt: addDaysISO(todayISO(), -26) + "T21:00:00.000Z",
  },
  {
    id: "rev_4",
    fromUserId: "u_maya",
    toUserId: "u_ben",
    itemId: "it_tent",
    requestId: "req_3",
    rating: 5,
    comment: "Ben walked me through the setup over chat. Tent was clean and dry. Highly recommended lender.",
    createdAt: addDaysISO(todayISO(), -1) + "T19:00:00.000Z",
  },
  {
    id: "rev_5",
    fromUserId: "u_ana",
    toUserId: "u_jose",
    itemId: "it_drill",
    rating: 4,
    comment: "Drill had plenty of power. One battery drains faster than the other but Jose mentioned it upfront.",
    createdAt: addDaysISO(todayISO(), -14) + "T10:00:00.000Z",
  },
  {
    id: "rev_6",
    fromUserId: "u_ben",
    toUserId: "u_maya",
    itemId: "it_bike",
    requestId: "req_1",
    rating: 5,
    comment: "Picked up on time, returned the bike cleaned and chain lubed. A trustworthy borrower.",
    createdAt: addDaysISO(todayISO(), -1) + "T08:00:00.000Z",
  },
];

/* ---------------------------------------------------------- notifications */

export const seedNotifications: AppNotification[] = [
  {
    id: "n_1",
    userId: "u_maya",
    type: "request_approved",
    title: "Your tent request was approved",
    message: "Ben Tan approved your borrowing request for the 6-Person Camping Tent. Coordinate pickup at your convenience.",
    read: false,
    createdAt: addDaysISO(todayISO(), -2) + "T14:30:00.000Z",
    link: { view: "dashboard" },
  },
  {
    id: "n_2",
    userId: "u_maya",
    type: "return_reminder",
    title: "Mountain Bike due in 2 days",
    message: "Friendly reminder — the Mountain Bike you borrowed from Ben Tan is due back on " + addDaysISO(todayISO(), 2) + ".",
    read: false,
    createdAt: addDaysISO(todayISO(), 0) + "T08:00:00.000Z",
    link: { view: "dashboard" },
  },
  {
    id: "n_3",
    userId: "u_maya",
    type: "review_received",
    title: "Ben left you a 5-star review",
    message: "Ben Tan rated you 5 stars as a borrower. Your trust score went up!",
    read: false,
    createdAt: addDaysISO(todayISO(), -1) + "T08:05:00.000Z",
    link: { view: "profile" },
  },
  {
    id: "n_4",
    userId: "u_maya",
    type: "request_received",
    title: "New borrow request pending",
    message: "Wait — this is just a heads up that you sent a request for Jose's power drill. We'll ping you when he responds.",
    read: true,
    createdAt: addDaysISO(todayISO(), 0) + "T07:35:00.000Z",
    link: { view: "dashboard" },
  },
  {
    id: "n_5",
    userId: "u_maya",
    type: "system",
    title: "Welcome to LendLoop, kapitbahay!",
    message: "Your account is verified. You can now lend, borrow, and build trust in Barangay Mabini.",
    read: true,
    createdAt: "2024-02-10T08:30:00.000Z",
    link: { view: "browse" },
  },
];

/* Notifications for the admin account (used when demo-switching to admin). */
export const seedAdminNotifications: AppNotification[] = [
  {
    id: "na_1",
    userId: "u_admin",
    type: "system",
    title: "2 new users this week",
    message: "Community growth is steady. Mark Aguilar and Gina Rocero onboarded lenders this week.",
    read: false,
    createdAt: addDaysISO(todayISO(), -1) + "T09:00:00.000Z",
    link: { view: "admin-users" },
  },
  {
    id: "na_2",
    userId: "u_admin",
    type: "system",
    title: "1 user flagged for late return",
    message: "Tony Bautista has a late-return flag. Review his activity and trust trend.",
    read: false,
    createdAt: addDaysISO(todayISO(), -1) + "T09:05:00.000Z",
    link: { view: "admin-users" },
  },
  {
    id: "na_3",
    userId: "u_admin",
    type: "system",
    title: "Monthly report ready",
    message: "The November community report is available with top lenders and most-borrowed items.",
    read: true,
    createdAt: addDaysISO(todayISO(), -2) + "T08:00:00.000Z",
    link: { view: "admin-reports" },
  },
];
